import type { ModelDef } from "../profiles/types.js";
import type { Provider } from "./types.js";

/** Options for constructing a `LlamaProvider` (providers spec §3.2). */
export interface LlamaProviderOptions {
  /** Base URL of the llama.cpp server, e.g. `http://localhost:8080`. */
  url: string;
  /**
   * The provider's name, used for disambiguation in model-selection specs
   * and `/model` output. Omitted → auto-generated by the registry
   * (e.g., `"llama_0"`, `"llama_1"`, …). Must be unique across all
   * registered providers.
   */
  name?: string;
  /**
   * API key sent as `Authorization: Bearer <key>` to the server. Omitted →
   * `""` (no auth). Used for servers started with `--api-key`.
   */
  apiKey?: string;
}

/** One entry of llama.cpp's `GET /v1/models` response (wire shape). */
interface LlamaModelEntry {
  id: string;
  /** llama.cpp metadata; `n_ctx` is the runtime context window in tokens. */
  meta?: { n_ctx?: number };
}

/** The `GET /v1/models` response body (wire shape). */
interface LlamaModelsResponse {
  data?: LlamaModelEntry[];
}

/**
 * A `Provider` for an OpenAI-compatible llama.cpp server (providers spec
 * §3.2).
 *
 * The server must be running and started with `--jinja` for tool calling.
 * The provider queries `GET {url}/v1/models` to discover loaded models. In
 * router mode (one server, many models), a single `LlamaProvider` yields one
 * `ModelDef` per discovered model.
 */
export class LlamaProvider implements Provider {
  /** Set by the registry at `addProvider()` time when left empty here. */
  name: string;
  /** The server's base URL, exposed for diagnostics (e.g. the E-P1 warning). */
  readonly baseUrl: string;
  private readonly apiKey: string;

  constructor(options: LlamaProviderOptions) {
    this.baseUrl = options.url;
    this.name = options.name ?? "";
    this.apiKey = options.apiKey ?? "";
  }

  async discoverModels(): Promise<ModelDef[]> {
    const endpoint = `${this.baseUrl.replace(/\/$/, "")}/v1/models`;
    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.apiKey) headers.Authorization = `Bearer ${this.apiKey}`;

    let response: Response;
    try {
      response = await fetch(endpoint, { method: "GET", headers });
    } catch {
      return [];
    }
    if (!response.ok) return [];

    let data: LlamaModelsResponse;
    try {
      data = (await response.json()) as LlamaModelsResponse;
    } catch {
      return [];
    }
    if (!Array.isArray(data.data)) return [];

    return data.data
      .filter(
        (entry): entry is LlamaModelEntry =>
          typeof entry?.id === "string" && entry.id.length > 0,
      )
      .map((entry) => {
        // llama.cpp reports the runtime context window as `meta.n_ctx` on each
        // /v1/models entry. Surface it as the model's `maxContext` so the
        // session stops defaulting to 8192; omit it when absent/invalid so a
        // non-llama backend (or an older server) falls back to the default.
        const nCtx = entry.meta?.n_ctx;
        return {
          name: entry.id,
          baseUrl: this.baseUrl,
          apiKey: this.apiKey,
          ...(typeof nCtx === "number" && Number.isInteger(nCtx) && nCtx > 0
            ? { maxContext: nCtx }
            : {}),
        };
      });
  }
}
