import { unlink } from "node:fs/promises";
import { join } from "node:path";
import type { Hook, HookContext } from "../hooks/types.js";
import type { ModelDef } from "../profiles/types.js";
import type { ModelAdmission, Provider } from "./types.js";

/** Options for constructing a `LlamaProvider` (providers spec §3.2). */
export interface LlamaProviderOptions {
  /** Base URL of the llama.cpp server, e.g. `http://localhost:8080`. */
  url: string;
  /**
   * The provider's name, used for disambiguation in model-selection specs
   * and `/model` output. Omitted → auto-generated by the registry
   * (e.g., `"llama_0"`, `"llama_1"`, …). Must be unique across all
   * registered providers.
   */
  name?: string;
  /**
   * API key sent as `Authorization: Bearer <key>` to the server. Omitted →
   * `""` (no auth). Used for servers started with `--api-key`.
   */
  apiKey?: string;
  /**
   * Opt in to KV persistence across subagent calls (KV spec §3.1): the
   * spawning agent's prompt cache is saved to disk before a subagent runs and
   * restored afterwards, so it never re-prefills its conversation. Default:
   * `false` — no save/restore, exactly the behavior of v0.2.0.
   */
  kvPersistence?: boolean;
  /** The llama.cpp slot id to save/restore. Default: `0`. */
  slotId?: number;
  /**
   * The directory the llama.cpp server was started with via `--slot-save-path`.
   * REQUIRED when `kvPersistence` is true (used to delete cache files via
   * `node:fs`). The save/restore HTTP calls themselves need only the filename;
   * this path is needed for deletion because llama.cpp exposes no file-delete
   * endpoint.
   */
  slotSavePath?: string;
  /**
   * Where KV save/restore warnings go. Defaults to stderr. Every failure is
   * fail-open (KV spec §3.8), so this is the only trace one leaves.
   */
  log?: (message: string) => void;
  /**
   * Where KV save/restore success notices go. Defaults to stdout, so the user
   * sees the cache being saved and loaded in the terminal. Kept separate from
   * `log` (stderr) so informational output never mixes with warnings.
   */
  note?: (message: string) => void;
  /**
   * Free VRAM in MiB right now, or `null` when it cannot be determined
   * (v0.10.0 spec §3.3).
   *
   * llama.cpp exposes no device memory over HTTP — `/props` carries the slot
   * count and nothing about memory, and `/v1/models` reports a model's size only
   * once it is already loaded. So the VRAM half of the capacity check has to come
   * from the host, and Vise will not shell out to a GPU tool itself: that would
   * make a platform-neutral harness depend on `nvidia-smi`. Supply the probe if
   * you want VRAM checked, e.g.
   *
   * ```ts
   * freeVramMiB: () =>
   *   Number(
   *     runCommand(
   *       "nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits",
   *     ).stdout.trim(),
   *   )
   * ```
   *
   * Omitted → VRAM is never checked and only the slot count gates a switch.
   * A callback that throws is treated exactly like one returning `null`.
   */
  freeVramMiB?: () => Promise<number | null> | number | null;
}

/** One entry of llama.cpp's `GET /v1/models` response (wire shape). */
interface LlamaModelEntry {
  id: string;
  /**
   * llama.cpp metadata; `n_ctx` is the runtime context window in tokens.
   * Present only once the model is actually loaded — a router lists models it
   * has never loaded, and those entries carry no `meta` at all. The presence of
   * `meta` is therefore what marks an entry as *resident*.
   */
  meta?: {
    n_ctx?: number;
    /**
     * The model's size in **bytes** — weights only, excluding the KV cache and
     * compute buffers, so it is a floor on what the model costs once resident.
     */
    size?: number;
  };
}

/** The `GET /v1/models` response body (wire shape). */
interface LlamaModelsResponse {
  data?: LlamaModelEntry[];
}

/** The `GET /props` response body, narrowed to what we read (wire shape). */
interface LlamaPropsResponse {
  /** `"router"` on a multi-model router, absent on a plain single-model server. */
  role?: string;
  default_generation_settings?: { n_ctx?: number };
  /**
   * Router mode only: how many models the server can hold resident at once,
   * i.e. what it was started with as `--models-max`.
   */
  max_instances?: number;
}

/** The cache file owned by the agent at `depth` (KV spec §3.8). */
export function kvCacheFileName(depth: number): string {
  return `kv-depth-${depth}.bin`;
}

/**
 * A `Provider` for an OpenAI-compatible llama.cpp server (providers spec
 * §3.2).
 *
 * The server must be running and started with `--jinja` for tool calling. The
 * provider queries `GET {url}/v1/models` to discover loaded models. In router
 * mode (one server, many models), a single `LlamaProvider` yields one
 * `ModelDef` per discovered model.
 *
 * With `kvPersistence: true` it also contributes one hook (KV spec §3.2) that
 * saves the slot's prompt cache before every nested `runTurn` and restores it
 * afterwards, so an agent that spawns a subagent does not re-prefill its
 * conversation when the subagent returns.
 */
export class LlamaProvider implements Provider {
  /** Set by the registry at `addProvider()` time when left empty here. */
  name: string;
  /** The server's base URL, exposed for diagnostics (e.g. the E-P1 warning). */
  readonly baseUrl: string;
  private readonly apiKey: string;
  /** Whether this provider saves/restores the slot KV around subagent runs. */
  readonly kvPersistence: boolean;
  private readonly slotId: number;
  private readonly slotSavePath: string;
  private readonly log: (message: string) => void;
  private readonly note: (message: string) => void;
  /** The host's free-VRAM probe, or `undefined` when VRAM is not checked. */
  private readonly freeVramMiB?: () => Promise<number | null> | number | null;
  /**
   * `max_instances` once it has been read successfully. Static for a server's
   * lifetime, so it is worth caching — but only a *positive* reading is stored:
   * a momentarily unreachable server must not poison the cache for the session.
   */
  private cachedSlotCount: number | null = null;
  /**
   * Sizes in bytes, learned from `meta.size` whenever a `/v1/models` response
   * happens to carry one. Only loaded models report it, so a model that has
   * never been resident stays unknown — which the gate treats as "allow".
   */
  private readonly modelSizes = new Map<string, number>();
  /**
   * The depths whose `subagent:before` save actually succeeded. A restore is
   * only attempted for a depth in this set, so a failed save is never followed
   * by a restore of a file that was never written (KV spec §3.5.4).
   */
  private readonly savedDepths = new Set<number>();
  /**
   * The contributed hook, built once. `hooks()` is called for every
   * materialized session, and every one of them must share `savedDepths`.
   */
  private kvHooks: Hook[] | null = null;

  constructor(options: LlamaProviderOptions) {
    this.baseUrl = options.url;
    this.name = options.name ?? "";
    this.apiKey = options.apiKey ?? "";
    this.kvPersistence = options.kvPersistence === true;
    this.slotId = options.slotId ?? 0;
    this.slotSavePath = options.slotSavePath ?? "";
    this.log =
      options.log ?? ((message) => process.stderr.write(`${message}\n`));
    this.note =
      options.note ?? ((message) => process.stdout.write(`${message}\n`));
    this.freeVramMiB = options.freeVramMiB;

    // KV spec §3.1: without the directory the provider cannot delete its cache
    // files, which would leave the disk dirty — a fatal config error, not a
    // warning.
    if (this.kvPersistence && this.slotSavePath === "") {
      throw new Error(
        `LlamaProvider: "slotSavePath" is required when "kvPersistence" is ` +
          `true. Pass the directory the llama.cpp server was started with ` +
          `via --slot-save-path, e.g. new LlamaProvider({ url: "${this.baseUrl}", ` +
          `kvPersistence: true, slotSavePath: "/path/to/llama-slots" }).`,
      );
    }
  }

  /**
   * KV spec §3.7: with one slot and depth-keyed cache files, two subagents at
   * the same depth would save and restore the same file, so the concurrent
   * `spawn_subagent` rule is suspended while KV persistence is on.
   */
  get serializeSubagents(): boolean {
    return this.kvPersistence;
  }

  async discoverModels(): Promise<ModelDef[]> {
    const endpoint = `${this.endpointBase()}/v1/models`;
    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.apiKey) headers.Authorization = `Bearer ${this.apiKey}`;

    let response: Response;
    try {
      response = await fetch(endpoint, { method: "GET", headers });
    } catch {
      return [];
    }
    if (!response.ok) return [];

    let data: LlamaModelsResponse;
    try {
      data = (await response.json()) as LlamaModelsResponse;
    } catch {
      return [];
    }
    if (!Array.isArray(data.data)) return [];
    this.learnSizes(data);

    return data.data
      .filter(
        (entry): entry is LlamaModelEntry =>
          typeof entry?.id === "string" && entry.id.length > 0,
      )
      // Discovery reports *where* each model lives, never how big its window
      // is: on a router every model here may still be unloaded, and the window
      // is only chosen at load time. `contextWindow()` asks later instead.
      .map((entry) => ({
        name: entry.id,
        baseUrl: this.baseUrl,
        apiKey: this.apiKey,
      }));
  }

  /**
   * The context window `model` is currently running with, or `null` when the
   * server cannot say yet (v0.9.0 spec §2, §3).
   *
   * Two read-only sources, in order:
   *  1. `GET /v1/models` → the entry's `meta.n_ctx`, which a router fills in
   *     once the model is loaded. This is the per-model answer.
   *  2. `GET /props` → `default_generation_settings.n_ctx`, the window of a
   *     plain single-model server's slots. Skipped in router mode, where the
   *     value describes the router itself (and is 0) rather than any model.
   *
   * Neither request loads anything — `GET /props?model=…` would, so it is
   * deliberately not used. Every failure is `null`, never a throw.
   */
  async contextWindow(model: string): Promise<number | null> {
    const models = await this.getJson<LlamaModelsResponse>("/v1/models");
    this.learnSizes(models);
    const entry = models?.data?.find((candidate) => candidate?.id === model);
    const fromModel = positiveInt(entry?.meta?.n_ctx);
    if (fromModel !== null) return fromModel;

    const props = await this.getJson<LlamaPropsResponse>("/props");
    if (props === null || props.role === "router") return null;
    return positiveInt(props.default_generation_settings?.n_ctx);
  }

  /**
   * Whether `model` can be loaded alongside what this server already holds
   * (v0.10.0 spec §3).
   *
   * Two conditions, both required, and both read-only:
   *  1. a free **model slot** — `/props` → `max_instances` against the number of
   *     entries `/v1/models` reports as resident (an entry carries `meta` only
   *     once it is loaded);
   *  2. enough **VRAM** — but only when the host supplied a `freeVramMiB` probe
   *     *and* the model's size has been learned. llama.cpp reports neither device
   *     memory nor an unloaded model's size, so either being unknown means the
   *     slot check stands alone rather than blocking a run on a guess.
   *
   * Never forces a load: asking the server to load the model to find out whether
   * it fits would evict the very model this check exists to protect.
   */
  async admitModel(model: string): Promise<ModelAdmission | null> {
    const models = await this.getJson<LlamaModelsResponse>("/v1/models");
    if (models === null) return null;
    this.learnSizes(models);

    const loaded: string[] = [];
    for (const entry of models.data ?? []) {
      if (typeof entry?.id === "string" && entry.id !== "" && entry.meta) {
        loaded.push(entry.id);
      }
    }

    // Already resident: using it costs nothing and evicts nothing.
    if (loaded.includes(model)) return { ok: true, loaded };

    const slots = await this.readSlotCount();
    if (slots === null) {
      return {
        ok: false,
        reason: "does not report how many models it can hold at once",
        loaded,
      };
    }
    if (loaded.length >= slots) {
      return {
        ok: false,
        reason: `has no free model slot (${loaded.length} of ${slots} in use)`,
        loaded,
      };
    }

    const free = await this.readFreeVram();
    const size = this.modelSizes.get(model);
    if (free === null || size === undefined) return { ok: true, loaded };

    const needMiB = Math.ceil(size / (1024 * 1024));
    if (needMiB <= free) return { ok: true, loaded };
    return {
      ok: false,
      reason: `does not have enough free VRAM (needs ~${needMiB} MiB, ${free} MiB free)`,
      loaded,
    };
  }

  /**
   * `max_instances` from `/props`, or `null` when the server genuinely will not
   * say. A plain (non-router) server omits the field because it holds exactly one
   * model, which is an answer of 1 rather than an unknown.
   */
  private async readSlotCount(): Promise<number | null> {
    if (this.cachedSlotCount !== null) return this.cachedSlotCount;

    const props = await this.getJson<LlamaPropsResponse>("/props");
    const reported = positiveInt(props?.max_instances);
    if (reported !== null) {
      this.cachedSlotCount = reported;
      return reported;
    }
    if (props !== null && props.role !== "router") {
      this.cachedSlotCount = 1;
      return 1;
    }
    return null;
  }

  /**
   * The host's free-VRAM reading in MiB, or `null` when there is no probe or it
   * cannot say. The probe is user code on a path contracted never to throw, so a
   * throw is caught here and reported as "unknown" like any other failure.
   */
  private async readFreeVram(): Promise<number | null> {
    if (this.freeVramMiB === undefined) return null;
    try {
      const value = await this.freeVramMiB();
      return typeof value === "number" && Number.isFinite(value) && value >= 0
        ? Math.floor(value)
        : null;
    } catch {
      return null;
    }
  }

  /** Record any `meta.size` a `/v1/models` response happens to carry. */
  private learnSizes(models: LlamaModelsResponse | null): void {
    for (const entry of models?.data ?? []) {
      const size = positiveInt(entry?.meta?.size);
      if (typeof entry?.id === "string" && entry.id !== "" && size !== null) {
        this.modelSizes.set(entry.id, size);
      }
    }
  }

  /** `GET {base}{path}` as JSON, or `null` for any failure. */
  private async getJson<T>(path: string): Promise<T | null> {
    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.apiKey) headers.Authorization = `Bearer ${this.apiKey}`;
    try {
      const response = await fetch(`${this.endpointBase()}${path}`, {
        method: "GET",
        headers,
      });
      if (!response.ok) return null;
      return (await response.json()) as T;
    } catch {
      return null;
    }
  }

  /**
   * The KV persistence hook (KV spec §3.2), or none when the feature is off.
   *
   * One hook subscribed to both subagent events, firing at every depth: the
   * save/restore stack needs the *spawning* agent's depth, and that agent may
   * itself be a subagent.
   */
  hooks(): Hook[] {
    if (!this.kvPersistence) return [];
    this.kvHooks ??= [
      {
        events: ["subagent:before", "subagent:after"],
        includeSubagents: true,
        handler: (ctx) => this.onSubagentEvent(ctx),
      },
    ];
    return this.kvHooks;
  }

  /** Save on the way into a nested run, restore on the way out. */
  private async onSubagentEvent(ctx: HookContext): Promise<void> {
    if (ctx.event === "subagent:before") {
      await this.saveSlot(ctx.depth, ctx.model);
    } else if (ctx.event === "subagent:after") {
      await this.restoreSlot(ctx.depth, ctx.model);
    }
  }

  /**
   * KV spec §3.4: write the slot's prompt cache to `kv-depth-{N}.bin`, freeing
   * the slot for the subagent. A failure is a warning: the subagent still
   * runs and this agent re-prefills afterwards.
   */
  private async saveSlot(depth: number, model?: string): Promise<void> {
    // A stale entry would let a failed save be followed by a restore of the
    // previous run's file, so clear it before trying.
    this.savedDepths.delete(depth);
    if (await this.slotAction("save", depth, model)) {
      this.savedDepths.add(depth);
      this.noteMessage(`KV cache saved to ${kvCacheFileName(depth)}`);
    }
  }

  /**
   * KV spec §3.5: read `kv-depth-{N}.bin` back into the slot and delete it.
   * Skipped entirely when the matching save failed — there is nothing on disk
   * to restore.
   */
  private async restoreSlot(depth: number, model?: string): Promise<void> {
    if (!this.savedDepths.delete(depth)) return;
    if (!(await this.slotAction("restore", depth, model))) return;

    const path = join(this.slotSavePath, kvCacheFileName(depth));
    try {
      await unlink(path);
    } catch (err) {
      // §4: the file may linger until the next run at this depth overwrites
      // it; the turn is unaffected.
      this.warn(`could not delete ${path}: ${messageOf(err)}`);
    }
    this.noteMessage(`KV cache restored from ${kvCacheFileName(depth)}`);
  }

  /**
   * `POST /slots/{id}?action=save|restore` with `{"filename": …, "model": …}`.
   * The `model` field is required by a llama.cpp *router* (one server, many
   * models), which needs it to know which model's slot to act on; a plain
   * single-model server ignores it. Returns whether the server accepted it;
   * every failure mode is fail-open and only produces a warning (KV spec §3.8).
   */
  private async slotAction(
    action: "save" | "restore",
    depth: number,
    model?: string,
  ): Promise<boolean> {
    const filename = kvCacheFileName(depth);
    const endpoint = `${this.endpointBase()}/slots/${this.slotId}?action=${action}`;
    const body = JSON.stringify({
      filename,
      ...(model !== undefined && model !== "" ? { model } : {}),
    });
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (this.apiKey) headers.Authorization = `Bearer ${this.apiKey}`;

    let response: Response;
    try {
      response = await fetch(endpoint, {
        method: "POST",
        headers,
        body,
      });
    } catch (err) {
      this.warn(`KV ${action} of ${filename} failed: ${messageOf(err)}`);
      return false;
    }

    const responseBody = await response.text();
    if (!response.ok) {
      // 501 is the server saying it was started without --slot-save-path.
      const hint =
        response.status === 501
          ? " (start llama-server with --slot-save-path DIR)"
          : "";
      this.warn(
        `KV ${action} of ${filename} failed: HTTP ${response.status}${hint} body=${responseBody}`,
      );
      return false;
    }
    return true;
  }

  /** The base URL without a trailing slash. */
  private endpointBase(): string {
    return this.baseUrl.endsWith("/")
      ? this.baseUrl.slice(0, -1)
      : this.baseUrl;
  }

  /** Report a fail-open problem, tagged with the provider it came from. */
  private warn(message: string): void {
    this.log(`[${this.name || "llama"}] ${message}`);
  }

  /** Report a successful save/restore, tagged with the provider it came from. */
  private noteMessage(message: string): void {
    this.note(`[${this.name || "llama"}] ${message}`);
  }
}

/** `value` when it is a usable token count, else `null`. */
function positiveInt(value: unknown): number | null {
  return typeof value === "number" && Number.isInteger(value) && value > 0
    ? value
    : null;
}

/** The message of a thrown value, whatever was thrown. */
function messageOf(err: unknown): string {
  if (err instanceof Error && err.message) return err.message;
  return String(err);
}
