/**
 * The provider abstraction (providers spec §3.1).
 *
 * A provider is a config-time convention, not a graph node: it is registered
 * via `reg.addProvider()` and used by the harness at startup to discover the
 * models a backend has available. It cannot be the source or target of a
 * `Connection` and never appears in `ResourceGraph.resources`.
 */
import type { Hook } from "../hooks/types.js";
import type { ModelDef } from "../profiles/types.js";

export interface Provider {
  /**
   * The provider's name. Used for disambiguation in model-selection specs
   * and `/model` output. Auto-generated by the registry if not supplied at
   * construction time. Unique across all registered providers.
   */
  readonly name: string;

  /**
   * Discover the models available from this provider. Called once at
   * startup by the harness. Each returned `ModelDef` must have a non-empty
   * `name` and `baseUrl`.
   *
   * Implementations MUST be idempotent, and must never throw for an
   * unreachable backend or an empty/malformed response — those conditions
   * are reported by returning `[]`, which the harness treats as "this
   * provider contributed no models" (providers spec §4, E-P1).
   */
  discoverModels(): Promise<ModelDef[]>;

  /**
   * Hooks this provider contributes to every session that runs against one of
   * its models, at every subagent depth (KV spec §3.2, §8.2).
   *
   * They are merged into the session's `HookManager` in addition to the
   * profile's own hooks — the one sanctioned exception to "hooks are never
   * global". Providers still are not graph nodes: the contribution happens at
   * materialization time, through this method, not through an edge.
   *
   * Called once per materialized session, so an implementation that keeps
   * per-hook state must return the same hook objects every time. Default:
   * none.
   */
  hooks?(): Hook[];

  /**
   * Ask the backend what context window `model` is currently running with, in
   * tokens (v0.9.0 spec §2, §3).
   *
   * The window is a property of a *loaded* model on a server, not of a model
   * definition: a llama.cpp router lists models it has never loaded, and with
   * `--fit on` the window is only chosen at load time from the memory actually
   * available. So this is asked lazily, after a completion has forced the load,
   * and may be asked again later.
   *
   * Implementations MUST be read-only — never force a load — and MUST never
   * throw: "cannot say (yet)" is reported by resolving to `null`. Default:
   * absent, i.e. the backend never reports one and only `setRuntime({
   * contextWindow })` can supply it.
   */
  contextWindow?(model: string): Promise<number | null>;

  /**
   * True when subagent runs must be serialized while this provider is active
   * (KV spec §3.7, §8.4).
   *
   * `spawn_subagent` is normally read-only, so several calls in one assistant
   * message run concurrently. A provider that keeps per-depth state around a
   * nested run — the llama.cpp KV cache, saved to one file per depth — cannot
   * survive two subagents at the same depth, and sets this so the calls run
   * one at a time instead. Default: `false` (unchanged, concurrent).
   */
  readonly serializeSubagents?: boolean;
}
