/**
 * The provider abstraction (providers spec §3.1).
 *
 * A provider is a config-time convention, not a graph node: it is registered
 * via `reg.addProvider()` and used by the harness at startup to discover the
 * models a backend has available. It cannot be the source or target of a
 * `Connection` and never appears in `ResourceGraph.resources`.
 */
import type { ModelDef } from "../profiles/types.js";

export interface Provider {
  /**
   * The provider's name. Used for disambiguation in model-selection specs
   * and `/model` output. Auto-generated by the registry if not supplied at
   * construction time. Unique across all registered providers.
   */
  readonly name: string;

  /**
   * Discover the models available from this provider. Called once at
   * startup by the harness. Each returned `ModelDef` must have a non-empty
   * `name` and `baseUrl`.
   *
   * Implementations MUST be idempotent, and must never throw for an
   * unreachable backend or an empty/malformed response — those conditions
   * are reported by returning `[]`, which the harness treats as "this
   * provider contributed no models" (providers spec §4, E-P1).
   */
  discoverModels(): Promise<ModelDef[]>;
}
